//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    using System;
    using System.Collections.Generic;

    public partial class SymptomTransport
    {
        public int ID { get; set; }
        public int App_Id { get; set; }
        public System.DateTime When { get; set; }
        public bool Pianto { get; set; }
        public bool Rigurgito { get; set; }
        public bool Agitazione { get; set; }
        public int Duration { get; set; }
        public int Intensity { get; set; }
        public int UserDataID { get; set; }

        public SymptomTransport() { }

        public SymptomTransport(Symptom symptom)
        {
            this.ID = symptom.ID;
            this.App_Id = symptom.App_Id;
            this.When = symptom.When;
            this.Pianto = symptom.Pianto;
            this.Rigurgito = symptom.Rigurgito;
            this.Agitazione = symptom.Agitazione;
            this.Duration = symptom.Duration;
            this.Intensity = symptom.Intensity;
            this.UserDataID = symptom.UserDataID;
        }
    }
}
