//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    using System;
    using System.Collections.Generic;

    public partial class SymptomTransport
    {
        public int ID { get; set; }
        public System.DateTime When { get; set; }
        public int Pianto { get; set; }
        public int Rigurgito { get; set; }
        public int Agitazione { get; set; }
        public int Duration { get; set; }
        public int Intensity { get; set; }
        public int UserDataID { get; set; }

        public SymptomTransport() { }

        public SymptomTransport(Symptom symptom)
        {
            this.ID = symptom.App_Id;
            this.When = symptom.When;
            this.Pianto = symptom.Pianto ? 1 : 0;
            this.Rigurgito = symptom.Rigurgito ? 1 : 0;
            this.Agitazione = symptom.Agitazione ? 1 : 0;
            this.Duration = symptom.Duration;
            this.Intensity = symptom.Intensity;
            this.UserDataID = symptom.UserDataID;
        }
    }
}
