//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    public partial class UserDataTransport
    {
        public int ID { get; set; }
        public int App_Id { get; set; }
        public string Name { get; set; }
        public string PatientPID { get; set; }
        public string DeviceToken { get; set; }
        public string OS { get; set; }

        public UserDataTransport() { }

        public UserDataTransport(UserData userData)
        {
            this.ID = userData.ID;
            this.App_Id = userData.App_Id;
            this.Name = userData.Name;
            this.PatientPID = userData.PatientPID;
            this.DeviceToken = userData.DeviceToken;
            this.OS = userData.OS;
        }
    }
}
