//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    public partial class UserDataTransport
    {
        public int ID { get; set; } //the App ID
        public int? PatientId { get; set; } //The Server ID
        public string Name { get; set; }
        public string PatientPID { get; set; }
        public string DeviceToken { get; set; }
        public string DeviceOS { get; set; }
        public string DeviceOSVersion { get; set; }

        public UserDataTransport() { }

        public UserDataTransport(UserData userData)
        {
            this.ID = userData.App_Id;
            this.PatientId = userData.ID;
            this.Name = userData.Name;
            this.PatientPID = userData.PatientPID;
            this.DeviceToken = userData.DeviceToken;
            this.DeviceOS = userData.DeviceOS;
            this.DeviceOSVersion = userData.DeviceOSVersion;
        }
    }
}
