//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotificationServer
{
    using System;
    using System.Collections.Generic;

    public enum NotificationStatusEnum : int
    {
        Error = -1,
        ToSend = 0,
        Sent = 1
    }
    
    public partial class Notification
    {
        public int ID { get; set; }
        public NotificationStatusEnum Status { get; set; }
        public System.DateTime When { get; set; }
        public string Message { get; set; }
        public string DeviceToken { get; set; }
        public string DestinationOS { get; set; }
        public ConfigurationItem Configuration { get; set; }

        public Notification(System.Data.SqlClient.SqlDataReader oReader, ConfigurationItem config)
        {
            this.ID = (int)oReader["ID"];
            this.Status = (NotificationStatusEnum)oReader["Status"];
            this.When = DateTime.Parse(oReader["When"].ToString());
            this.Message = oReader["Message"].ToString();
            this.DeviceToken = oReader["DeviceToken"].ToString();
            this.DestinationOS = oReader["DestinationOS"].ToString();

            this.Configuration = config;
        }

        public bool isForAndroid()
        {
            return DestinationOS.Equals("android");
        }
    }
}
