//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Symptom> SymptomSet { get; set; }
        public DbSet<Appointment> AppointmentSet { get; set; }
        public DbSet<Pill> PillSet { get; set; }
        public DbSet<PillAlert> PillAlertSet { get; set; }
        public DbSet<UserData> UserDataSet { get; set; }
        public DbSet<Notification> NotificationSet { get; set; }
    }
}
