//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pill
    {
        public int Id { get; set; }
        public int App_Id { get; set; }
        public Nullable<int> Shape { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Info { get; set; }
        public bool Deletable { get; set; }
    }
}
