//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public UserData()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Symptoms = new HashSet<Symptom>();
            this.PillAlerts = new HashSet<PillAlert>();
        }
    
        public int ID { get; set; }
        public int App_Id { get; set; }
        public string Name { get; set; }
        public string PatientPID { get; set; }
        public string DeviceToken { get; set; }
        public string DeviceOS { get; set; }
        public string DeviceOSVersion { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Symptom> Symptoms { get; set; }
        public virtual ICollection<PillAlert> PillAlerts { get; set; }
    }
}
