//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColicheGassose
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int Id { get; set; }
        public int App_Id { get; set; }
        public System.DateTime When { get; set; }
        public bool Pianto { get; set; }
        public bool Rigurgito { get; set; }
        public bool Agitazione { get; set; }
        public int Duration { get; set; }
        public int Intensity { get; set; }
    }
}
